name: writeit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  flutter_launcher_icons: ^0.14.4
  go_router: ^16.2.4
  flutter_riverpod: ^3.0.1
  get_it: ^8.2.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  image_picker: 1.2.0
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_storage: ^13.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/publisher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
     - assets/icons/publisher.png
     - assets/images/writing.png
     - assets/images/google.png
     - assets/images/publishing.png






  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
